/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCategories"];
        put?: never;
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCategoryBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateCategory"];
        post?: never;
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAllRecipesForAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnyRecipeForAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublishedRecipes"];
        put?: never;
        post: operations["createRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchPublishedRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedRecipeBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRecipe"];
        post?: never;
        delete: operations["deleteRecipe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["publishRecipe"];
        trace?: never;
    };
    "/recipes/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["unpublishRecipe"];
        trace?: never;
    };
    "/recipes/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["archiveRecipe"];
        trace?: never;
    };
    "/recipes/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["unarchiveRecipe"];
        trace?: never;
    };
    "/me/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyRecipes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyRecipe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadRecipeImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteRecipeImage"];
        options?: never;
        head?: never;
        patch: operations["updateRecipeImage"];
        trace?: never;
    };
    "/recipes/{id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRecipeStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/steps/{stepId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRecipeStep"];
        post?: never;
        delete: operations["deleteRecipeStep"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRecipeIngredient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}/ingredients/{ingredientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRecipeIngredient"];
        post?: never;
        delete: operations["deleteRecipeIngredient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{imageId}/{variant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Published media is public; Draft/Archived media requires owner or Admin authorization. */
        get: operations["getRecipeImageVariant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            displayName: string;
            /** Format: email */
            email: string;
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        UpdateProfileRequest: {
            displayName?: string;
            /** Format: uri */
            avatarUrl?: string | null;
            bio?: string | null;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            /** Format: uri */
            avatarUrl?: string | null;
            bio?: string | null;
            roles: ("Author" | "Admin")[];
            emailConfirmed?: boolean;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        UserEnvelope: {
            data: components["schemas"]["User"];
        };
        AuthEnvelope: {
            data: {
                accessToken: string;
                refreshToken: string;
                /** Format: date-time */
                expiresAt: string;
                user: components["schemas"]["User"];
            };
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            /** Format: uri */
            imageUrl?: string | null;
            orderIndex: number;
            recipeCount: number;
        };
        CategoryWrite: {
            name: string;
            description?: string | null;
            /** Format: uri */
            imageUrl?: string | null;
            orderIndex?: number;
        };
        /** @enum {string} */
        RecipeStatus: "draft" | "published" | "archived";
        /** @enum {string} */
        RecipeDifficulty: "easy" | "medium" | "hard" | "expert";
        RecipeSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @description Server-generated; collisions receive -2 */
            slug: string;
            description: string;
            prepTime: number;
            cookTime: number;
            servings: number;
            difficulty: components["schemas"]["RecipeDifficulty"];
            status: components["schemas"]["RecipeStatus"];
            /** Format: uri */
            primaryImageUrl?: string | null;
            category: components["schemas"]["Category"];
            author: components["schemas"]["User"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: int64 */
            version: number;
        };
        RecipeDetail: components["schemas"]["RecipeSummary"] & {
            instructions?: string | null;
            nutrition?: {
                [key: string]: unknown;
            } | null;
            ingredients: components["schemas"]["Ingredient"][];
            steps: components["schemas"]["Step"][];
            images: components["schemas"]["RecipeImage"][];
        };
        CreateRecipeRequest: {
            title: string;
            description: string;
            /** Format: uuid */
            categoryId: string;
            prepTime: number;
            cookTime: number;
            servings: number;
            difficulty: components["schemas"]["RecipeDifficulty"];
            instructions?: string | null;
            nutrition?: {
                [key: string]: unknown;
            } | null;
            steps?: components["schemas"]["StepWrite"][];
            ingredients?: components["schemas"]["IngredientWrite"][];
        };
        UpdateRecipeRequest: components["schemas"]["CreateRecipeRequest"];
        StepWrite: {
            title: string;
            description: string;
            timerMinutes?: number | null;
            /** Format: uri */
            imageUrl?: string | null;
            /** @description Chỉ dùng khi PUT để đổi vị trí */
            stepNumber?: number;
        };
        Step: components["schemas"]["StepWrite"] & {
            /** Format: uuid */
            id: string;
        };
        IngredientWrite: {
            name: string;
            quantity?: number | null;
            unit?: string | null;
            notes?: string | null;
            /** @default 0 */
            orderIndex: number;
        };
        Ingredient: components["schemas"]["IngredientWrite"] & {
            /** Format: uuid */
            id: string;
        };
        RecipeImage: {
            /** Format: uuid */
            id: string;
            /** @description Controlled API media path */
            originalUrl?: string | null;
            /** @description Controlled API media path when ready */
            mediumUrl?: string | null;
            /** @description Controlled API media path when ready */
            thumbnailUrl?: string | null;
            altText?: string | null;
            isPrimary: boolean;
            orderIndex: number;
            /** @enum {string} */
            processingStatus?: "pending" | "ready" | "failed";
        };
        ChildMutationEnvelope: {
            data: components["schemas"]["Ingredient"] | components["schemas"]["Step"] | components["schemas"]["RecipeImage"];
            meta: {
                /** Format: int64 */
                recipeVersion: number;
            };
        };
        PageMeta: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
        RecipePage: {
            data: components["schemas"]["RecipeSummary"][];
            meta: components["schemas"]["PageMeta"];
        };
        CategoryDetailEnvelope: {
            data: {
                category: components["schemas"]["Category"];
                recipes: components["schemas"]["RecipeSummary"][];
            };
            meta: components["schemas"]["PageMeta"];
        };
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            code: string;
            errors?: {
                [key: string]: string[];
            };
            correlationId: string;
            traceId: string;
        };
    };
    responses: {
        /** @description RFC 7807 Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Account created and session issued */
        AuthCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthEnvelope"];
            };
        };
        /** @description Session issued */
        AuthOk: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthEnvelope"];
            };
        };
        /** @description Category resource */
        CategoryResource: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data: components["schemas"]["Category"];
                };
            };
        };
        /** @description Recipe resource */
        RecipeResource: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    data: components["schemas"]["RecipeDetail"];
                };
            };
        };
        /** @description Paged recipe results; public operations constrain data to Published */
        RecipePage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RecipePage"];
            };
        };
        /** @description Recipe child resource created or updated */
        ChildMutation: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ChildMutationEnvelope"];
            };
        };
    };
    parameters: {
        Id: string;
        Slug: string;
        Page: number;
        PageSize: number;
        Sort: string;
        /** @description Quoted aggregate version ETag */
        IfMatch: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: components["responses"]["AuthCreated"];
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["AuthOk"];
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            423: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    idToken: string;
                };
            };
        };
        responses: {
            200: components["responses"]["AuthOk"];
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            200: components["responses"]["AuthOk"];
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Refresh token đã được revoke hoặc vốn không còn hiệu lực */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hồ sơ hiện tại */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Hồ sơ đã cập nhật */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách category, sắp xếp name tăng dần */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Category"][];
                    };
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWrite"];
            };
        };
        responses: {
            201: components["responses"]["CategoryResource"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getCategoryBySlug: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category và Published recipes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDetailEnvelope"];
                };
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryWrite"];
            };
        };
        responses: {
            200: components["responses"]["CategoryResource"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category đã soft-delete */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listAllRecipesForAdmin: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["RecipeStatus"];
                authorId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipePage"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getAnyRecipeForAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipeResource"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listPublishedRecipes: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                sort?: components["parameters"]["Sort"];
                categoryId?: string;
                difficulty?: components["schemas"]["RecipeDifficulty"];
                maxCookTime?: number;
                minServings?: number;
                minPrepTime?: number;
                maxPrepTime?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipePage"];
            400: components["responses"]["Problem"];
        };
    };
    createRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecipeRequest"];
            };
        };
        responses: {
            201: components["responses"]["RecipeResource"];
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    searchPublishedRecipes: {
        parameters: {
            query?: {
                q?: string;
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                /** @description Category slug */
                category?: string;
                difficulty?: components["schemas"]["RecipeDifficulty"];
                /** @description Maximum preparation plus cooking time in minutes */
                maxTime?: number;
                sort?: "relevance" | "newest" | "quickest" | "az";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipePage"];
            400: components["responses"]["Problem"];
        };
    };
    getPublishedRecipeBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipeResource"];
            404: components["responses"]["Problem"];
        };
    };
    updateRecipe: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecipeRequest"];
            };
        };
        responses: {
            200: components["responses"]["RecipeResource"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    deleteRecipe: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe đã soft-delete */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    publishRecipe: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipeResource"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    unpublishRecipe: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipeResource"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    archiveRecipe: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipeResource"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    unarchiveRecipe: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipeResource"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    listMyRecipes: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["RecipeStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipePage"];
            401: components["responses"]["Problem"];
        };
    };
    getMyRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RecipeResource"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    uploadRecipeImage: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    altText?: string | null;
                    /** @default false */
                    isPrimary?: boolean;
                };
            };
        };
        responses: {
            201: components["responses"]["ChildMutation"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    deleteRecipeImage: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image metadata deleted; object deletion queued */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    updateRecipeImage: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
                imageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    altText?: string | null;
                    isPrimary?: boolean;
                    orderIndex?: number;
                };
            };
        };
        responses: {
            200: components["responses"]["ChildMutation"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    createRecipeStep: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepWrite"];
            };
        };
        responses: {
            201: components["responses"]["ChildMutation"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    updateRecipeStep: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
                stepId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepWrite"];
            };
        };
        responses: {
            200: components["responses"]["ChildMutation"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    deleteRecipeStep: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
                stepId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Step deleted; remaining steps renumbered */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    createRecipeIngredient: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientWrite"];
            };
        };
        responses: {
            201: components["responses"]["ChildMutation"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    updateRecipeIngredient: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
                ingredientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientWrite"];
            };
        };
        responses: {
            200: components["responses"]["ChildMutation"];
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    deleteRecipeIngredient: {
        parameters: {
            query?: never;
            header: {
                /** @description Quoted aggregate version ETag */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["Id"];
                ingredientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingredient deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    getRecipeImageVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                imageId: string;
                variant: "original" | "medium" | "thumbnail";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate healthy status without topology details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Aggregate unhealthy status */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PostgreSQL and Redis ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
